pull_request_rules:
        
  - name: automatic merge 2.6.x on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=2.6.x
      - label=merge-when-green
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        strict: smart

  - name: automatic merge 2.7.x on CI success
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - base=2.7.x
      - label=merge-when-green
      - label!=work-in-progress
    actions:
      merge:
        method: merge
        strict: smart

  - name: delete branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: remove label after merge
    conditions:
      - merged
      - label=[merge-when-green]
    actions:
      label:
        remove: [merge-when-green]