#!/usr/bin/env bash

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
rm -f test.mv.db
sbt ++$TRAVIS_SCALA_VERSION clean flyway/flywayMigrate slickCodegen test
