#!/usr/bin/env bash

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
rm -f test.mv.db
sbt ++$MATRIX_SCALA clean flyway/flywayMigrate slickCodegen test
