#!/usr/bin/env bash

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
rm -f test.mv.db test.trace.db
sbt ++$MATRIX_SCALA clean reload ++$MATRIX_SCALA flyway/flywayMigrate slickCodegen test
