#!/usr/bin/env bash

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/script-helper"

# Use travis scala version or defaults to 2.12.4
SCALA_VERSION=${TRAVIS_SCALA_VERSION:-"2.12.4"}

# Using cut because $SCALA_VERSION is the full Scala
# version (for example 2.12.4), but Gradle expects just the
# binary version (for example 2.12)
scala_binary_version=$(echo $SCALA_VERSION | cut -c1-4)

echo "+------------------------------+"
echo "| Executing tests using Gradle |" 
echo "+------------------------------+"
./gradlew -Dscala.binary.version=$scala_binary_version check -i --stacktrace
