#!/usr/bin/env bash

set -e
set -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/../../.." && pwd)"

"$repo_root/run-sbt-command" "++$MATRIX_SCALA" test docs/paradox
"$repo_root/run-sbt-command" "++$MATRIX_SCALA" ";project gatling;gatling:compile"
