---
apiVersion: v1
kind: Service
metadata:
  labels:
    appName: "play-scala-grpc-example"
  name: "play-scala-grpc-example"
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
    - name: https
      port: 9443
      protocol: TCP
  selector:
    appName: "play-scala-grpc-example"
