---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yml
- ../../base/service.yml
- ingress.yml

## The minikube kustomization doesn't doe anything because the deployment.yml has all the right defaults.
#images:
#- name: "play-java-grpc-example"
#  newName: "play-java-grpc-example"
#  newTag: "1.0-SNAPSHOT"