#!/usr/bin/env bash

. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/script-helper"

echo "+------------------------------+"
echo "| Executing tests using Gradle |" 
echo "+------------------------------+"
./gradlew check -i --stacktrace
