#!/usr/bin/env bash

echo "+----------------------------+"
echo "| Executing tests using sbt  |"
echo "+----------------------------+"
sbt ++$TRAVIS_SCALA_VERSION clean flyway/flywayMigrate slickCodegen test
