#!/usr/bin/env bash

set -e
set -o pipefail

echo "+------------------------------+"
echo "| Executing tests using Gradle |" 
echo "+------------------------------+"
# Using cut because TRAVIS_SCALA_VERSION is the full Scala
# version (for example 2.12.4), but Gradle expects just the
# binary version (for example 2.12)
./gradlew -Dscala.binary.version=`echo $TRAVIS_SCALA_VERSION | cut -c1-4` test -i