---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base/
resources:
  - route.yml


images:
- name: "play-java-grpc-example"
  newName: "my-docker-registry.mycompany.com/play-java-grpc-example/play-java-grpc-example"
  newTag: "1.0-SNAPSHOT"