name: Publish

on:
  push:
    branches: # Snapshots
      - 3.0.x

jobs:
  publish-sources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Package sources
        run: |
          ./sources.sh
      - name: Delete Release
        run: gh release delete v3.0.x --cleanup-tag || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish sources
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: v3.0.x
          tag_name: v3.0.x
          target_commitish: ${{ github.ref_name }}
          files: |
            *-example.zip
            *-tutorial.zip
          fail_on_unmatched_files: true
