#!/usr/bin/env bash

export KEY_PASSWORD=`cat scripts/password` 

echo "+----------------------------+"
echo "| Executing tests using sbt  |" 
echo "+----------------------------+"
sbt ++$TRAVIS_SCALA_VERSION test
