#!/usr/bin/env bash

export KEY_PASSWORD=`cat scripts/password` 

echo "+---------------------------------------+"
echo "| Executing tests using (modified sbt)  |"
echo "+---------------------------------------+"
./play ++$MATRIX_SCALA test
